server:
  port: 8000
  servlet:
    context-path: /dc

#配置数据源
spring:
  jpa:
    show-sql: true
    platform: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          fetch_size: 200
          batch_size: 50
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:eladmin}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: ${DB_USER:root}
    password: ${DB_PWD:123456}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
    continue-on-error: true
    initialization-mode: always
    data: classpath:db-init.sql
  data:
    redis:
      repositories:
        enabled: false
  redis:
    #数据库索引
    database: ${REDIS_DB:0}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:}
    #连接超时时间
    timeout: 5000

# 登录相关配置
login:
  # 登录缓存
  cache-enable: true
  #  是否限制单用户登录
  single-login: false
  #  验证码
  login-code:
    #  验证码类型配置 查看 LoginProperties 类
    code-type: arithmetic
    #  登录图形验证码有效时间/分钟
    expiration: 2
    #  验证码高度
    width: 111
    #  验证码宽度
    height: 36
    # 内容长度
    length: 2
    # 字体名称，为空则使用默认字体
    font-name:
    # 字体大小
    font-size: 25

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEA6DrIUm9WVfh/3Lf0MxdV8yrsPSrYdxP4Dy3kL9LnekBd9EHFpv4TcgGAbo3gMsJUV5csqWNWzAyhlI7b8/+jtQIDAQABAkBPD/QzXIRgMIIXeulAm6k/aFWVXYjkwX+qa01MmtkD3VAJiqmOrZSzHVdDjOCiKDJr5AUDL4K9jz5MBz0eqywBAiEA+p2hyX7KqeABlBxg5y2b/avj1u64rthidPiuA5w7UmECIQDtOAc2VgN1rbJVgExRDpgyRnmW0RpjJL/K0N5yBZy51QIgFKJt870wypPbDWrYv7ANq/E/LS8ynZLLaH4hNcLjT4ECIA46jRwyPpThbU/5mRpHkNN7LLHiKv4FZ0eoDZ+zPHpdAiEAumZqAPKjmthiMnHqA4Psq6704+rGtY90
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000

# 文件存储路径
file:
  mac:
    path: ~/file/
    avatar: ~/avatar/
  linux:
    path: /home/eladmin/file/
    avatar: /home/eladmin/avatar/
  windows:
    path: C:\eladmin\file\
    avatar: C:\eladmin\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50
#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15
#邮箱验证码有效时间/秒
code:
  expiration: 300
#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==

